os:
  - linux
language: c
compiler:
 - clang
 - gcc
addons:
  apt:
    packages:
      check
      libtalloc-dev
  brew:
    packages:
      check
      talloc
script:
 - cmake .
 - make
 - make check
 - ./check

