arch:
  - amd64
  - arm64
os:
  - linux
  - osx
language: c
compiler:
 - clang
 - gcc
addons:
  apt:
    packages:
      check
      libtalloc-dev
  homebrew:
    packages:
    - check
    - talloc
    update: true
script:
 - cmake .
 - make
 - make check
 - ./check

